### PR TITLE
 Move to default ports (80 and 443) for container manger UI 

### PR DESCRIPTION
**Pull request by Toshbrown**

### CODE REVIEW

**Comment by Toshbrown** [comment]
@jptmoore can you take a look at why the core store is failing to build, please. Sorry, John it the core-network that is failing.

@sevenEng can you take a look. please. [Log](https://travis-ci.org/me-box/databox/builds/316640033?utm_source=github_status&utm_medium=notification)

@ktg can you update the Apps to use 80 and 443

**Comment by sevenEng** [comment]
A PR is on the fly for this: https://github.com/ocaml/opam-repository/pull/11039

**Comment by ktg** [comment]
Ok. I've just uploaded a beta version of the app that will connect to Databox over default ports. 
However, the Mac OS firewall does not allow external connections on privileged ports like 80 and 443. I could not find any way of allowing this other than disabling the firewall.
Stupid Macs

**Comment by Toshbrown** [comment]
https://github.com/me-box/databox/pull/216/commits/35c250a41e2c7cb8ad264f809d5da94561b1ecc0 Fixes https://github.com/me-box/databox/issues/210 on @tlodge MacOS el capitan mac

**Comment by Toshbrown** [comment]
@sevenEng looks like PR https://github.com/ocaml/opam-repository/pull/11039 was merged. 

core-network is still failing to build, with this error now:

```
Your request can't be satisfied:

  - nocrypto.0.5.4 is in conflict with topkg.0.9.0


No solution found, exiting FAILED
```

**Pull request merged**
