### PR TITLE
databox with core-network

### PR DESCRIPTION
**Pull request by sevenEng**
#### changes in brief:
- CM, arbiter, export-service, bridge are put on `databox-system-net` created in start script
- arbiter, export-service are configured to use `dnsrr` as endpoint-mode, see about [Virtual IP](https://github.com/me-box/admin/blob/master/reports/2017/41/seveneng.md)
- make bridge one of CM's dns resolvers *(as when contact apps/drivers etc. behind the bridge)*

#### more to come:
- [x] use compose file to start bridge *(like with app-server)*
- [x] put export-service on another network which could access outside world, or make `databox-system-net` not `--internal`
- [x] rethink the name of the bridge, as the concept may be overloaded already, causing confusions

#### to test:
Has to be tested together with [this PR](https://github.com/me-box/core-container-manager/pull/9) on CM, and the bridge hasn't been transferred yet, need to be cloned and built separately: https://github.com/sevenEng/databox-bridge.

ATM, it passes checks from `databox-test`, but will test more, in terms of multiple apps/drivers, removes and reinstall and such

### CODE REVIEW

**Comment by Toshbrown** [comment]
RE: check if could use compose file to start bridge 

You can use a compose file, it needs to outside of the swarm right?

**Comment by sevenEng** [comment]
Yes, and also need a secret to be mapped in. I'll try it out.

**Comment by Toshbrown** [comment]
Secrets are only accessible from within the swarm :-(  

You could just write the key to a file (by adding it [here](https://github.com/me-box/databox/blob/master/src/config.json#L3) ) and map it into the container using volumes.

edit: just spotted this is how you do it at the minute 👍

**Comment by sevenEng** [comment]
log from failed travis build:
```
[2017-11-01T11:39:10+0000 databox-test]: Starting build store-json ...
The command '/bin/sh -c echo http://dl-4.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories && apk add --no-cache mongodb && apk add --no-cache nodejs-current-npm && rm /usr/bin/mongoperf' returned a non-zero code: 1
[2017-11-01T11:39:19+0000 databox-test]: Build store-json 
ERROR: Sending build context to Docker daemon  175.1kB
Step 1/11 : FROM alpine:edge
edge: Pulling from library/alpine
e00d546a75ad: Pulling fs layer
e00d546a75ad: Verifying Checksum
e00d546a75ad: Download complete
e00d546a75ad: Pull complete
Digest: sha256:166f9a1803cc56882a9ca528f9b12936d72e6c1adbc0db3e60447db4c15ddd51
Status: Downloaded newer image for alpine:edge
 ---> 631c9b7258b2
Step 2/11 : RUN echo http://dl-4.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories && apk add --no-cache mongodb && apk add --no-cache nodejs-current-npm && rm /usr/bin/mongoperf
 ---> Running in b78268d11b60
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://dl-4.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
(1/18) Installing boost-system (1.62.0-r5)
(2/18) Installing libgcc (6.4.0-r5)
(3/18) Installing boost-filesystem (1.62.0-r5)
(4/18) Installing boost-regex (1.62.0-r5)
(5/18) Installing boost-thread (1.62.0-r5)
(6/18) Installing libstdc++ (6.4.0-r5)
(7/18) Installing boost (1.62.0-r5)
(8/18) Installing libbz2 (1.0.6-r6)
(9/18) Installing boost-iostreams (1.62.0-r5)
(10/18) Installing boost-program_options (1.62.0-r5)
(11/18) Installing pcre (8.41-r1)
(12/18) Installing libpcrecpp (8.41-r1)
(13/18) Installing db (5.3.28-r0)
(14/18) Installing libsasl (2.1.26-r10)
(15/18) Installing snappy (1.1.4-r2)
(16/18) Installing wiredtiger-libs (2.9.3.3.4.6-r0)
(17/18) Installing yaml-cpp (0.5.3-r3)
(18/18) Installing mongodb (3.4.9-r0)
Executing mongodb-3.4.9-r0.pre-install
Executing busybox-1.27.2-r2.trigger
OK: 142 MiB in 29 packages
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://dl-4.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  nodejs-current-npm (virtual):
    provided by: nodejs-npm
    required by: world[nodejs-current-npm] FAILED
```
so no `nodejs-current-npm` for x86 from alpine's `edge` branch?
seems consistent with this search: https://pkgs.alpinelinux.org/packages?name=nodejs-current-npm&branch=edge&repo=&arch=&maintainer=
they are removed from the `edge` branch recently? not sure what happened here @Toshbrown

**Comment by Toshbrown** [comment]
Builds fixed 👍

**Comment by sevenEng** [comment]
Ha, thanks! :smile:

**Pull request merged**
